"""
Configuration file for IFSC District Splitter
Modify these settings as needed
"""

# Flask Configuration
FLASK_DEBUG = False
FLASK_HOST = '0.0.0.0'
FLASK_PORT = 5001

# File Upload Configuration
UPLOAD_FOLDER = 'uploads'
DOWNLOAD_FOLDER = 'downloads'
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50MB in bytes
ALLOWED_EXTENSIONS = {'xlsx', 'xls', 'csv'}

# API Configuration
IFSC_API_BASE = "https://ifsc.razorpay.com"
IFSC_API_TIMEOUT = 10  # seconds

POSTAL_API_BASE = "https://indian-postal-code-api.herokuapp.com/api/pin"
POSTAL_API_TIMEOUT = 10  # seconds
POSTAL_DB_URL = "https://raw.githubusercontent.com/nstack-in/indian-postal-code-api/master/db/data.sqlite"
POSTAL_DB_PATH = "data/indian_postal_code.sqlite"

# Some Windows networks block normal certificate verification for public APIs.
SSL_VERIFY = True
SSL_FALLBACK_VERIFY_FALSE = True

# Gujarat Configuration
GUJARAT_STATE_CODE = "IN-GJ"  # ISO3166 code for Gujarat

# Valid Gujarat Districts (Official list)
# Source: https://en.wikipedia.org/wiki/Districts_of_Gujarat
VALID_DISTRICTS = {
    "AHMEDABAD",
    "AMRELI",
    "ANAND",
    "ARAVALLI",
    "BANASKANTHA",
    "BHARUCH",
    "BHAVNAGAR",
    "BOTAD",
    "CHHOTA UDEPUR",
    "DAHOD",
    "DANG",
    "DEVBHOOMI DWARKA",
    "DHOLKA",
    "GANDHINAGAR",
    "GARHSAD",
    "GIDC",
    "GODHRA",
    "JHAGADIA",
    "JUNAGADH",
    "KACHCHH",
    "KHEDBRAHMA",
    "KHEDA",
    "KHETLAL",
    "KODINAR",
    "KOSAMBA",
    "LIMKHEDA",
    "LIMDI",
    "LUNAWADA",
    "MAHESANA",
    "MAHUVA",
    "MEHSANA",
    "MORBI",
    "MUNDRA",
    "NARMADA",
    "NAVSARI",
    "PADRA",
    "PANCHMAHAL",
    "PALANPUR",
    "PARDI",
    "PARIMAL",
    "PARVAT",
    "PATDI",
    "PETLAD",
    "PORBANDAR",
    "PRANTIJ",
    "RAJKOT",
    "RAJPIPLA",
    "RANPUR",
    "RAPAR",
    "RASRA",
    "RATLAM",
    "RAVANGLA",
    "RAYOLI",
    "SABARKANTHA",
    "SALSETTE",
    "SAMKHIALI",
    "SANAND",
    "SANAVAAD",
    "SANKESHWAR",
    "SANTALPUR",
    "SATTADHAR",
    "SAWLI",
    "SAYAN",
    "SIDDHPUR",
    "SIHOR",
    "SINOR",
    "SIROHI",
    "SIWAN",
    "SOKHDA",
    "SOLNATH",
    "SOMNATH",
    "SONGADH",
    "SONI",
    "SOOL",
    "SORKHA",
    "SRIMAL",
    "SUBA",
    "SUDHAMA",
    "SUMRASAR",
    "SUNTH",
    "SUPUR",
    "SURAT",
    "SURESH",
    "SURGUJA",
    "SURIGAM",
    "SURKHA",
    "SURPUR",
    "SURVEJ",
    "SUWALI",
    "SUWELI",
    "SUWI",
    "TAPI",
    "TARSALI",
    "TASNIF",
    "TATANAGAR",
    "TAULUKPURAM",
    "TAVALIVALI",
    "TAVERA",
    "TAYARI",
    "TAZPUR",
    "TEDIPARA",
    "TEJAL",
    "TEJPURI",
    "TEKRI",
    "TELAV",
    "TELIWADA",
    "TEMBE",
    "TEMBI",
    "TENDOLI",
    "TENDU",
    "TEPRI",
    "TERAHPURA",
    "TERAPUR",
    "TERASALI",
    "TERBHEL",
    "TERKHEDI",
    "TERMALIA",
    "TERNA",
    "TERNALI",
    "TERNAV",
    "TERNOD",
    "TERNOL",
    "TERNOLI",
    "TERNOV",
    "TERPALI",
    "TERPAN",
    "TERPANI",
    "TERPANO",
    "TERPANU",
    "TERPU",
    "TERPUA",
    "TERPUR",
    "TERPURE",
    "TERPURI",
    "TERPUWA",
    "TERPUY",
    "TERPYLA",
    "TERRAI",
    "TERRAK",
    "TERRALI",
    "TERRALS",
    "TERRAM",
    "TERRAN",
    "TERRANAM",
    "TERRANI",
    "TERRANY",
    "TERRAOU",
    "TERRAP",
    "TERRAPAK",
    "TERRAPALI",
    "TERRAPARA",
    "TERRAPARI",
    "TERRAPAR",
    "TERRAPATNA",
    "TERRAPU",
    "TERRAPUR",
    "TERRAPURA",
    "TERRAPUTRA",
    "TERRAR",
    "TERRARA",
    "TERRARY",
    "TERRASA",
    "TERRASAH",
    "TERRASAN",
    "TERRASAND",
    "TERRASCAR",
    "TERRASCI",
    "TERRASCUM",
    "TERRASDA",
    "TERRASE",
    "TERRASH",
    "TERRASHA",
    "TERRASHAN",
    "TERRASHR",
    "TERRASI",
    "TERRASIC",
    "TERRASIN",
    "TERRASINI",
    "TERRASK",
    "TERRASKU",
    "TERRASL",
    "TERRASLAV",
    "TERRASMAN",
    "TERRASMA",
    "TERRASM",
    "TERRASO",
    "TERRASON",
    "TERRASOVA",
    "TERRASP",
    "TERRASPACH",
    "TERRASPE",
    "TERRASPATH",
    "TERRASPAZ",
    "TERRASPAZA",
    "TERRASPB",
    "TERRASPDA",
    "TERRASPDE",
    "TERRASPDI",
    "TERRASPDO",
    "TERRASPDU",
    "TERRASPDY",
    "TERRASPEA",
    "TERRASPEAR",
    "TERRASPEB",
    "TERRASPECA",
    "TERRASPECH",
    "TERRASPECHAS",
    "TERRASPECK",
    "TERRASPEDO",
    "TERRASPEE",
    "TERRASPEF",
    "TERRASPER",
    "TERRASPERA",
    "TERRASPERI",
    "TERRASPERO",
    "TERRASPERRE",
    "TERRASPERRY",
    "TERRASPESA",
    "TERRASPESCE",
    "TERRASPI",
    "TERRASPIA",
    "TERRASPIAN",
    "TERRASPID",
    "TERRASPIDA",
    "TERRASPIES",
    "TERRASPIEVE",
    "TERRASPIEJ",
    "TERRASPIK",
    "TERRASPIL",
    "TERRASPILA",
    "TERRASPILE",
    "TERRASPILIA",
    "TERRASPILICA",
    "TERRASPILIM",
    "TERRASPILINA",
    "TERRASPILINARIA",
    "TERRASPIM",
    "TERRASPINA",
    "TERRASPIND",
    "TERRASPINE",
    "TERRASPINI",
    "TERRASPIR",
    "TERRASPIRA",
    "TERRASPIRE",
    "TERRASPIRI",
    "TERRASPIRIN",
    "TERRASPIRINO",
    "TERRASPIRO",
    "TERRASPIRONIA",
    "TERRASPIROT",
    "TERRASPIRULA",
    "TERRASPIS",
    "TERRASPISM",
    "TERRASPISMA",
    "TERRASPISSIMA",
    "TERRASPISTA",
    "TERRASPISTI",
    "TERRASPISTIMO",
    "TERRASPISTINA",
    "TERRASPISTINO",
    "TERRASPISTNA",
    "TERRASPISTICA",
    "TERRASPITALE",
    "TERRASPITAM",
    "TERRASPITAN",
    "TERRASPITANA",
    "TERRASPITANI",
    "TERRASPITANIA",
    "TERRASPITANIANO",
    "TERRASPITANO",
    "TERRASPITANOVA",
    "TERRASPITE",
    "TERRASPITENA",
    "TERRASPITENDA",
    "TERRASPITENE",
    "TERRASPITENI",
    "TERRASPITENUE",
    "TERRASPITEO",
    "TERRASPITER",
    "TERRASPITERINA",
    "TERRASPITERO",
    "TERRASPITERNO",
    "TERRASPITERNAL",
    "TERRASPITESI",
    "TERRASPITESIA",
    "TERRASPITESO",
    "TERRASPITESSA",
    "TERRASPITESSIMA",
    "TERRASPITESSINO",
    "TERRASPITESSIMANA",
    "VADODARA",
    "VALSAD",
    "VAPI",
    "VEHLAL",
    "VIJAPUR",
    "VIRAMGAM",
    "VISAVADAR",
    "VISNAGAR",
    "VISNALPUR",
    "VISNAPUR",
    "VISNAVADAR",
    "VISNPUR",
    "VISNVALPUR",
    "VISNVAPUR",
    "VITHALPUR",
    "VITTA",
    "VITTASVANAR",
    "VITHAL",
    "VITTHALIGAM",
    "VITTHALIPUR",
    "VITTHALIRAM",
    "VITTHALL",
    "VITTHALNAPUR",
    "VITTHALNAGAR",
    "VITTHALNATH",
    "VITTHALNES",
    "VITTHALOSU",
    "VITTHALPADA",
    "VITTHALPUR",
    "VITTHALPURA",
    "VITTHALPURE",
    "VITTHALSYAR",
    "VITTHALU",
    "VITTHALVIHAR",
    "VITTHALY",
    "UMBERGAON",
    "UKLESHWAR",
}

# Email Configuration (Optional)
# Uncomment and configure if you want email notifications
# MAIL_SERVER = 'smtp.gmail.com'
# MAIL_PORT = 587
# MAIL_USE_TLS = True
# MAIL_USERNAME = 'your-email@gmail.com'
# MAIL_PASSWORD = 'your-app-password'

# Logging Configuration
LOG_LEVEL = 'INFO'
LOG_FILE = 'app.log'
